# Generated by Django 2.2.19 on 2021-06-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_transaction_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
