# Generated by Django 2.2.19 on 2021-06-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='slide',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
