# Generated by Django 2.2.19 on 2021-06-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_advert_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
